# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate rust-analyzer
%global tag 2023-03-06

Name:           rust-analyzer
Version:        20230306
Release:        %autorelease
Summary:        A Rust compiler front-end for IDEs

License:        MIT OR Apache-2.0
URL:            https://github.com/rust-lang/rust-analyzer
Source0:	https://github.com/rust-lang/rust-analyzer/archive/refs/tags/%{tag}.tar.gz

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A Rust compiler front-end for IDEs.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE-APACHE
%license LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{tag} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
