# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate heim

Name:           rust-heim
Version:        0.0.11
Release:        %autorelease
Summary:        Cross-platform framework for system information

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/heim
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Cross-platform framework for system information.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cpu-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cpu-devel %{_description}

This package contains library source intended for building other packages which
use the "cpu" feature of the "%{crate}" crate.

%files       -n %{name}+cpu-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+disk-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+disk-devel %{_description}

This package contains library source intended for building other packages which
use the "disk" feature of the "%{crate}" crate.

%files       -n %{name}+disk-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heim-cpu-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heim-cpu-devel %{_description}

This package contains library source intended for building other packages which
use the "heim-cpu" feature of the "%{crate}" crate.

%files       -n %{name}+heim-cpu-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heim-disk-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heim-disk-devel %{_description}

This package contains library source intended for building other packages which
use the "heim-disk" feature of the "%{crate}" crate.

%files       -n %{name}+heim-disk-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heim-host-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heim-host-devel %{_description}

This package contains library source intended for building other packages which
use the "heim-host" feature of the "%{crate}" crate.

%files       -n %{name}+heim-host-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heim-memory-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heim-memory-devel %{_description}

This package contains library source intended for building other packages which
use the "heim-memory" feature of the "%{crate}" crate.

%files       -n %{name}+heim-memory-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heim-net-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heim-net-devel %{_description}

This package contains library source intended for building other packages which
use the "heim-net" feature of the "%{crate}" crate.

%files       -n %{name}+heim-net-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heim-process-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heim-process-devel %{_description}

This package contains library source intended for building other packages which
use the "heim-process" feature of the "%{crate}" crate.

%files       -n %{name}+heim-process-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heim-sensors-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heim-sensors-devel %{_description}

This package contains library source intended for building other packages which
use the "heim-sensors" feature of the "%{crate}" crate.

%files       -n %{name}+heim-sensors-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heim-virt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heim-virt-devel %{_description}

This package contains library source intended for building other packages which
use the "heim-virt" feature of the "%{crate}" crate.

%files       -n %{name}+heim-virt-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+host-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+host-devel %{_description}

This package contains library source intended for building other packages which
use the "host" feature of the "%{crate}" crate.

%files       -n %{name}+host-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+memory-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+memory-devel %{_description}

This package contains library source intended for building other packages which
use the "memory" feature of the "%{crate}" crate.

%files       -n %{name}+memory-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+net-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+net-devel %{_description}

This package contains library source intended for building other packages which
use the "net" feature of the "%{crate}" crate.

%files       -n %{name}+net-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+process-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+process-devel %{_description}

This package contains library source intended for building other packages which
use the "process" feature of the "%{crate}" crate.

%files       -n %{name}+process-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-polyfill-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-polyfill-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-polyfill" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-polyfill-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sensors-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sensors-devel %{_description}

This package contains library source intended for building other packages which
use the "sensors" feature of the "%{crate}" crate.

%files       -n %{name}+sensors-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+virt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+virt-devel %{_description}

This package contains library source intended for building other packages which
use the "virt" feature of the "%{crate}" crate.

%files       -n %{name}+virt-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
