# Generated by rust2rpm 24
%bcond_without check

%global crate b3sum

Name:           rust-b3sum
Version:        1.3.3
Release:        %autorelease
Summary:        Command line implementation of the BLAKE3 hash function

License:        CC0-1.0 OR Apache-2.0
URL:            https://crates.io/crates/b3sum
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A command line implementation of the BLAKE3 hash function.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%doc README.md
%doc what_does_check_do.md
%{_bindir}/b3sum

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
