# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate uom

Name:           rust-uom
Version:        0.34.0
Release:        %autorelease
Summary:        Units of measurement

# Upstream license specification: Apache-2.0/MIT
License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/uom
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Units of measurement.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+autoconvert-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+autoconvert-devel %{_description}

This package contains library source intended for building other packages which
use the "autoconvert" feature of the "%{crate}" crate.

%files       -n %{name}+autoconvert-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bigint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bigint-devel %{_description}

This package contains library source intended for building other packages which
use the "bigint" feature of the "%{crate}" crate.

%files       -n %{name}+bigint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bigint-support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bigint-support-devel %{_description}

This package contains library source intended for building other packages which
use the "bigint-support" feature of the "%{crate}" crate.

%files       -n %{name}+bigint-support-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bigrational-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bigrational-devel %{_description}

This package contains library source intended for building other packages which
use the "bigrational" feature of the "%{crate}" crate.

%files       -n %{name}+bigrational-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+biguint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+biguint-devel %{_description}

This package contains library source intended for building other packages which
use the "biguint" feature of the "%{crate}" crate.

%files       -n %{name}+biguint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+complex-support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+complex-support-devel %{_description}

This package contains library source intended for building other packages which
use the "complex-support" feature of the "%{crate}" crate.

%files       -n %{name}+complex-support-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+complex32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+complex32-devel %{_description}

This package contains library source intended for building other packages which
use the "complex32" feature of the "%{crate}" crate.

%files       -n %{name}+complex32-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+complex64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+complex64-devel %{_description}

This package contains library source intended for building other packages which
use the "complex64" feature of the "%{crate}" crate.

%files       -n %{name}+complex64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+f32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+f32-devel %{_description}

This package contains library source intended for building other packages which
use the "f32" feature of the "%{crate}" crate.

%files       -n %{name}+f32-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+f64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+f64-devel %{_description}

This package contains library source intended for building other packages which
use the "f64" feature of the "%{crate}" crate.

%files       -n %{name}+f64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+i128-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+i128-devel %{_description}

This package contains library source intended for building other packages which
use the "i128" feature of the "%{crate}" crate.

%files       -n %{name}+i128-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+i16-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+i16-devel %{_description}

This package contains library source intended for building other packages which
use the "i16" feature of the "%{crate}" crate.

%files       -n %{name}+i16-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+i32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+i32-devel %{_description}

This package contains library source intended for building other packages which
use the "i32" feature of the "%{crate}" crate.

%files       -n %{name}+i32-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+i64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+i64-devel %{_description}

This package contains library source intended for building other packages which
use the "i64" feature of the "%{crate}" crate.

%files       -n %{name}+i64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+i8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+i8-devel %{_description}

This package contains library source intended for building other packages which
use the "i8" feature of the "%{crate}" crate.

%files       -n %{name}+i8-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+isize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+isize-devel %{_description}

This package contains library source intended for building other packages which
use the "isize" feature of the "%{crate}" crate.

%files       -n %{name}+isize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+num-bigint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+num-bigint-devel %{_description}

This package contains library source intended for building other packages which
use the "num-bigint" feature of the "%{crate}" crate.

%files       -n %{name}+num-bigint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+num-complex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+num-complex-devel %{_description}

This package contains library source intended for building other packages which
use the "num-complex" feature of the "%{crate}" crate.

%files       -n %{name}+num-complex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+num-rational-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+num-rational-devel %{_description}

This package contains library source intended for building other packages which
use the "num-rational" feature of the "%{crate}" crate.

%files       -n %{name}+num-rational-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rational-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rational-devel %{_description}

This package contains library source intended for building other packages which
use the "rational" feature of the "%{crate}" crate.

%files       -n %{name}+rational-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rational-support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rational-support-devel %{_description}

This package contains library source intended for building other packages which
use the "rational-support" feature of the "%{crate}" crate.

%files       -n %{name}+rational-support-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rational32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rational32-devel %{_description}

This package contains library source intended for building other packages which
use the "rational32" feature of the "%{crate}" crate.

%files       -n %{name}+rational32-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rational64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rational64-devel %{_description}

This package contains library source intended for building other packages which
use the "rational64" feature of the "%{crate}" crate.

%files       -n %{name}+rational64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+si-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+si-devel %{_description}

This package contains library source intended for building other packages which
use the "si" feature of the "%{crate}" crate.

%files       -n %{name}+si-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+try-from-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+try-from-devel %{_description}

This package contains library source intended for building other packages which
use the "try-from" feature of the "%{crate}" crate.

%files       -n %{name}+try-from-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+u128-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+u128-devel %{_description}

This package contains library source intended for building other packages which
use the "u128" feature of the "%{crate}" crate.

%files       -n %{name}+u128-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+u16-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+u16-devel %{_description}

This package contains library source intended for building other packages which
use the "u16" feature of the "%{crate}" crate.

%files       -n %{name}+u16-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+u32-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+u32-devel %{_description}

This package contains library source intended for building other packages which
use the "u32" feature of the "%{crate}" crate.

%files       -n %{name}+u32-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+u64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+u64-devel %{_description}

This package contains library source intended for building other packages which
use the "u64" feature of the "%{crate}" crate.

%files       -n %{name}+u64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+u8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+u8-devel %{_description}

This package contains library source intended for building other packages which
use the "u8" feature of the "%{crate}" crate.

%files       -n %{name}+u8-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_serde-devel %{_description}

This package contains library source intended for building other packages which
use the "use_serde" feature of the "%{crate}" crate.

%files       -n %{name}+use_serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+usize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+usize-devel %{_description}

This package contains library source intended for building other packages which
use the "usize" feature of the "%{crate}" crate.

%files       -n %{name}+usize-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
